// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1CJcesdsQ7kaBG-lnLsrvbldtHezYkts',
    appId: '1:830161752219:web:3ab897d96910721993363e',
    messagingSenderId: '830161752219',
    projectId: 'project1-6c75a',
    authDomain: 'project1-6c75a.firebaseapp.com',
    storageBucket: 'project1-6c75a.firebasestorage.app',
    measurementId: 'G-HFF4ZCPNHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBketQ7MAxsXgw_b99dKp6WgykMnkr7D1I',
    appId: '1:830161752219:android:8d8183b7be7358e293363e',
    messagingSenderId: '830161752219',
    projectId: 'project1-6c75a',
    storageBucket: 'project1-6c75a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtGxYdVB8t8sZbWPVJmnFx-zld8NzRMTE',
    appId: '1:830161752219:ios:d3ce6416784b8ab793363e',
    messagingSenderId: '830161752219',
    projectId: 'project1-6c75a',
    storageBucket: 'project1-6c75a.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtGxYdVB8t8sZbWPVJmnFx-zld8NzRMTE',
    appId: '1:830161752219:ios:d3ce6416784b8ab793363e',
    messagingSenderId: '830161752219',
    projectId: 'project1-6c75a',
    storageBucket: 'project1-6c75a.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1CJcesdsQ7kaBG-lnLsrvbldtHezYkts',
    appId: '1:830161752219:web:e64fda03951ad44793363e',
    messagingSenderId: '830161752219',
    projectId: 'project1-6c75a',
    authDomain: 'project1-6c75a.firebaseapp.com',
    storageBucket: 'project1-6c75a.firebasestorage.app',
    measurementId: 'G-PTHN0T9VHS',
  );
}
